# Generated by Django 2.2.7 on 2020-02-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='program',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='zip_code',
        ),
    ]
