# Generated by Django 2.2.7 on 2020-02-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200228_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
